 export const data=[
  {
    "id": "1",
    "videoId": "video01",
    "title": "Big Buck Bunny",
    "thumbnailUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png",
    "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png",
    "duration": "8:18",
    "views": "24,969,123",
    "author": "Vlc Media Player",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "description": "Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself. When one sunny day three rodents rudely harass him, something snaps... and the rabbit ain't no bunny anymore!",
    "subscriber": "25,254,545 Subscribers",
    "isLive": true,
    "channelId": "chA",
    "uploader": "userA",
    "likes": 1842,
    "dislikes": 37,
    "uploadDate": "2024-11-07",
    "comments": [
      {
        "commentId": "cmt1-1",
        "userId": "u101",
        "text": "This animation never gets old!",
        "timestamp": "2024-11-08T09:12:00Z"
      }
    ],
    "category": "Technology"
  },
  {
    "id": "2",
    "videoId": "video02",
    "title": "The first Blender Open Movie from 2006",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp",
    "duration": "12:18",
    "views": "24,969,123",
    "author": "Blender Inc.",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "description": "Song : Raja Raja Kareja Mein Samaja. Album : Raja Kareja Mein Samaja. Artist : Radhe Shyam Rasia.",
    "subscriber": "25,254,545 Subscribers",
    "isLive": true,
    "channelId": "chB",
    "uploader": "userB",
    "likes": 2920,
    "dislikes": 104,
    "uploadDate": "2025-02-14",
    "comments": [
      {
        "commentId": "cmt2-1",
        "userId": "u202",
        "text": "Great to see Blender history preserved.",
        "timestamp": "2025-02-15T12:05:00Z"
      }
    ],
    "category": "Technology"
  },
  {
    "id": "3",
    "videoId": "video03",
    "title": "For Bigger Blazes",
    "thumbnailUrl": "https://img.freepik.com/premium-photo/music-concept-with-headphones-musical-notes-copy-space-3d-illustration_522591-1950.jpg",
    "photo": "https://img.freepik.com/premium-photo/music-concept-with-headphones-musical-notes-copy-space-3d-illustration_522591-1950.jpg",
    "duration": "8:18",
    "views": "24,969,123",
    "author": "T-Series Regional",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "description": "Song : Raja Raja Kareja Mein Samaja. Album : Raja Kareja Mein Samaja. Artist : Radhe Shyam Rasia.",
    "subscriber": "25,254,545 Subscribers",
    "isLive": true,
    "channelId": "chC",
    "uploader": "userC",
    "likes": 5210,
    "dislikes": 210,
    "uploadDate": "2023-12-02",
    "comments": [
      {
        "commentId": "cmt3-1",
        "userId": "u303",
        "text": "Favorite track in this compilation!",
        "timestamp": "2023-12-03T18:45:00Z"
      }
    ],
    "category": "Music"
  },
  {
    "id": "4",
    "videoId": "video04",
    "title": "For Bigger Escape",
    "thumbnailUrl": "https://img.jakpost.net/c/2019/09/03/2019_09_03_78912_1567484272._large.jpg",
    "photo": "https://img.jakpost.net/c/2019/09/03/2019_09_03_78912_1567484272._large.jpg",
    "duration": "8:18",
    "views": "24,969,123",
    "author": "T-Series Regional",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "description": "Introducing Chromecast. The easiest way to enjoy online video and music on your TV—for when Batman's escapes aren't quite big enough.",
    "subscriber": "25,254,545 Subscribers",
    "isLive": false,
    "channelId": "chD",
    "uploader": "userD",
    "likes": 398,
    "dislikes": 12,
    "uploadDate": "2024-06-21",
    "comments": [
      {
        "commentId": "cmt4-1",
        "userId": "u404",
        "text": "Nice cameo in the ad!",
        "timestamp": "2024-06-22T07:30:00Z"
      }
    ],
    "category": "Music"
  },
  {
    "id": "5",
    "videoId": "video05",
    "title": "Big Buck Bunny",
    "thumbnailUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png",
    "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_thumbnail_vlc.png/1200px-Big_Buck_Bunny_thumbnail_vlc.png",
    "duration": "8:18",
    "views": "24,969,123",
    "author": "Vlc Media Player",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "description": "Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself. When one sunny day three rodents rudely harass him, something snaps... and the rabbit ain't no bunny anymore!",
    "subscriber": "25,254,545 Subscribers",
    "isLive": true,
    "channelId": "chE",
    "uploader": "userE",
    "likes": 760,
    "dislikes": 22,
    "uploadDate": "2024-03-11",
    "comments": [
      {
        "commentId": "cmt5-1",
        "userId": "u505",
        "text": "Rewatching this classic.",
        "timestamp": "2024-03-12T10:20:00Z"
      }
    ],
    "category": "Technology"
  },
  {
    "id": "6",
    "videoId": "video06",
    "title": "For Bigger Blazes",
    "thumbnailUrl": "https://i.ytimg.com/vi/Dr9C2oswZfA/maxresdefault.jpg",
    "photo": "https://elements-resized.envatousercontent.com/elements-preview-images/bf5516b3-3f66-45bf-bc9f-3a0cded19c47?w=632&cf_fit=scale-down&q=85&format=auto&s=86fa298e2fbba7024af0d31f42150c26ac54138e250e7a24017a60c4ca8985dd",
    "duration": "8:18",
    "views": "24,969,123",
    "author": "T-Series Regional",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "description": "Song : Raja Raja Kareja Mein Samaja. Album : Raja Kareja Mein Samaja.",
    "subscriber": "25,254,545 Subscribers",
    "isLive": false,
    "channelId": "chF",
    "uploader": "userF",
    "likes": 1320,
    "dislikes": 49,
    "uploadDate": "2024-08-05",
    "comments": [
      {
        "commentId": "cmt6-1",
        "userId": "u606",
        "text": "Nice arrangement.",
        "timestamp": "2024-08-06T14:00:00Z"
      }
    ],
    "category": "Music"
  },
  {
    "id": "7",
    "videoId": "video07",
    "title": "For Bigger Escape",
    "thumbnailUrl": "https://img.jakpost.net/c/2019/09/03/2019_09_03_78912_1567484272._large.jpg",
    "photo": "https://img.jakpost.net/c/2019/09/03/2019_09_03_78912_1567484272._large.jpg",
    "duration": "8:18",
    "views": "24,969,123",
    "author": "T-Series Regional",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "description": "Introducing Chromecast. The easiest way to enjoy online video and music on your TV—for when Batman's escapes aren't quite big enough.",
    "subscriber": "25,254,545 Subscribers",
    "isLive": true,
    "channelId": "chG",
    "uploader": "userG",
    "likes": 2210,
    "dislikes": 88,
    "uploadDate": "2025-01-19",
    "comments": [
      {
        "commentId": "cmt7-1",
        "userId": "u707",
        "text": "Great production value.",
        "timestamp": "2025-01-20T20:45:00Z"
      }
    ],
    "category": "Music"
  },
  {
    "id": "8",
    "videoId": "video08",
    "title": "The first Blender Open Movie from 2006",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/gWw23EYM9VM/maxresdefault.webp",
    "duration": "12:18",
    "views": "24,969,123",
    "author": "Blender Inc.",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "description": "Song : Raja Raja Kareja Mein Samaja. Album : Raja Kareja Mein Samaja. Artist : Radhe Shyam Rasia.",
    "subscriber": "25,254,545 Subscribers",
    "isLive": false,
    "channelId": "chH",
    "uploader": "userH",
    "likes": 640,
    "dislikes": 18,
    "uploadDate": "2023-05-28",
    "comments": [
      {
        "commentId": "cmt8-1",
        "userId": "u808",
        "text": "Lovely restoration!",
        "timestamp": "2023-05-29T11:10:00Z"
      }
    ],
    "category": "Technology"
  },

  
  {
    "id": "9",
    "videoId": "game01",
    "title": "Top 10 Impossible Gaming Moments",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/1w7OgIMMRc4/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/1w7OgIMMRc4/maxresdefault.webp",
    "duration": "08:45",
    "views": "12,453,221",
    "author": "GameWorld",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    "description": "Compilation of the craziest gaming plays in history!",
    "subscriber": "3,240,411 Subscribers",
    "isLive": false,
    "channelId": "chGaming",
    "uploader": "UserG1",
    "likes": 540,
    "dislikes": 12,
    "uploadDate": "2024-01-10",
    "comments": [
      {
        "commentId": "cmt-g1",
        "userId": "u001",
        "text": "This was insane!",
        "timestamp": "2024-01-11T09:00:00Z"
      }
    ],
    "category": "Gaming"
  },

  {
    "id": "10",
    "videoId": "ball01",
    "title": "NBA Best Plays of 2024",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/9jK-NcRmVcw/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/9jK-NcRmVcw/maxresdefault.webp",
    "duration": "10:21",
    "views": "8,231,210",
    "author": "NBA Highlights",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "description": "A full breakdown of the best dunks, passes and buzzer beaters.",
    "subscriber": "12,450,000 Subscribers",
    "isLive": false,
    "channelId": "chBall",
    "uploader": "UserB1",
    "likes": 821,
    "dislikes": 19,
    "uploadDate": "2024-02-08",
    "comments": [
      {
        "commentId": "cmt-b1",
        "userId": "u202",
        "text": "Unbelievable!",
        "timestamp": "2024-02-09T12:30:00Z"
      }
    ],
    "category": "Basketball"
  },

  {
    "id": "11",
    "videoId": "music01",
    "title": "Relaxing Piano Music • Study & Sleep",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/2OEL4P1Rz04/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/2OEL4P1Rz04/maxresdefault.webp",
    "duration": "03:12:10",
    "views": "65,210,900",
    "author": "Dream Music",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    "description": "Soft and peaceful piano melodies.",
    "subscriber": "4,650,789 Subscribers",
    "isLive": false,
    "channelId": "chMusic",
    "uploader": "UserM1",
    "likes": 920,
    "dislikes": 8,
    "uploadDate": "2023-11-20",
    "comments": [
      {
        "commentId": "cmt-m1",
        "userId": "u333",
        "text": "So peaceful.",
        "timestamp": "2023-11-21T14:10:00Z"
      }
    ],
    "category": "Music"
  },

  {
    "id": "12",
    "videoId": "news01",
    "title": "Global News Update – Top Headlines",
    "thumbnailUrl": "https://tse1.mm.bing.net/th/id/OIP.FH8L-4RQzsyrejj0C3cS2QHaE8?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
    "photo": "https://tse1.mm.bing.net/th/id/OIP.FH8L-4RQzsyrejj0C3cS2QHaE8?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
    "duration": "05:12",
    "views": "2,340,921",
    "author": "World News",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    "description": "Daily global news summary.",
    "subscriber": "8,455,000 Subscribers",
    "isLive": true,
    "channelId": "chNews",
    "uploader": "UserN1",
    "likes": 188,
    "dislikes": 4,
    "uploadDate": "2024-02-28",
    "comments": [],
    "category": "News"
  },

  {
    "id": "13",
    "videoId": "movie01",
    "title": "Top Sci-Fi Movies to Watch in 2025",
    "thumbnailUrl": "https://images.squarespace-cdn.com/content/v1/538de52be4b0ac20b46b210c/0535662b-61c3-42c2-8bbe-217f3df268b7/2023-3d-movies.jpg",
    "photo": "https://images.squarespace-cdn.com/content/v1/538de52be4b0ac20b46b210c/0535662b-61c3-42c2-8bbe-217f3df268b7/2023-3d-movies.jpg",
    "duration": "14:58",
    "views": "4,120,991",
    "author": "MovieSpot",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    "description": "Best upcoming science-fiction movies.",
    "subscriber": "1,451,290 Subscribers",
    "isLive": false,
    "channelId": "chMovies",
    "uploader": "UserMV1",
    "likes": 650,
    "dislikes": 11,
    "uploadDate": "2024-01-05",
    "comments": [],
    "category": "Movies"
  },

  {
    "id": "14",
    "videoId": "com01",
    "title": "Funniest Stand-up Clips of 2024",
    "thumbnailUrl": "https://img.freepik.com/premium-photo/vibrant-3d-artwork-comedy-youtuber-creating-funny-content-ai-generated-illustration_866663-52219.jpg",
    "photo": "https://img.freepik.com/premium-photo/vibrant-3d-artwork-comedy-youtuber-creating-funny-content-ai-generated-illustration_866663-52219.jpg",
    "duration": "09:34",
    "views": "18,240,550",
    "author": "LaughHub",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
    "description": "Best jokes and moments from top comedians.",
    "subscriber": "9,510,000 Subscribers",
    "isLive": false,
    "channelId": "chComedy",
    "uploader": "UserC1",
    "likes": 870,
    "dislikes": 21,
    "uploadDate": "2024-02-10",
    "comments": [],
    "category": "Comedy"
  },

  {
    "id": "15",
    "videoId": "fit01",
    "title": "10-Minute Morning Workout for Beginners",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/UBMk30rjy0o/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/UBMk30rjy0o/maxresdefault.webp",
    "duration": "10:00",
    "views": "9,211,002",
    "author": "Fitness Pro",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "description": "Perfect morning workout to stay fit.",
    "subscriber": "3,420,000 Subscribers",
    "isLive": false,
    "channelId": "chFit",
    "uploader": "UserF1",
    "likes": 430,
    "dislikes": 5,
    "uploadDate": "2024-01-15",
    "comments": [],
    "category": "Fitness"
  },

  {
    "id": "16",
    "videoId": "code01",
    "title": "Learn React in 30 Minutes",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/bMknfKXIFA8/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/bMknfKXIFA8/maxresdefault.webp",
    "duration": "30:00",
    "views": "5,443,210",
    "author": "CodeStack",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    "description": "React tutorial for beginners.",
    "subscriber": "980,100 Subscribers",
    "isLive": false,
    "channelId": "chCode",
    "uploader": "UserCD1",
    "likes": 770,
    "dislikes": 13,
    "uploadDate": "2024-02-01",
    "comments": [],
    "category": "Coding"
  },

  {
    "id": "17",
    "videoId": "pod01",
    "title": "The Mindset Podcast – Episode 12",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/Ga6RYejo6Hk/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/Ga6RYejo6Hk/maxresdefault.webp",
    "duration": "42:30",
    "views": "1,120,143",
    "author": "Mindset Talks",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    "description": "Deep conversation on productivity and mindset.",
    "subscriber": "410,000 Subscribers",
    "isLive": false,
    "channelId": "chPod",
    "uploader": "UserP1",
    "likes": 300,
    "dislikes": 6,
    "uploadDate": "2024-01-22",
    "comments": [],
    "category": "Podcasts"
  },

  {
    "id": "18",
    "videoId": "trend01",
    "title": "Top Viral Videos of This Week",
    "thumbnailUrl": "https://i.ytimg.com/vi/8jTboLfXtac/maxresdefault.jpg",
    "photo": "https://i.ytimg.com/vi/8jTboLfXtac/maxresdefault.jpg",
    "duration": "07:55",
    "views": "22,943,223",
    "author": "TrendSpot",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "description": "Compilation of everything trending this week.",
    "subscriber": "2,230,000 Subscribers",
    "isLive": false,
    "channelId": "chTrend",
    "uploader": "UserT1",
    "likes": 910,
    "dislikes": 15,
    "uploadDate": "2024-03-01",
    "comments": [],
    "category": "Trending"
  },

  {
    "id": "19",
    "videoId": "watch01",
    "title": "Your Recently Watched Playlist",
    "thumbnailUrl": "https://img.freepik.com/free-vector/realistic-science-youtube-channel_23-2149074838.jpg?t=st=1724552293~exp=1724555893~hmac=55a1de87be1b7e1f429411f972bbfc03fc1a3536fa36fa0c2b6ed43b923bd41c",
    "photo": "https://img.freepik.com/free-vector/realistic-science-youtube-channel_23-2149074838.jpg?t=st=1724552293~exp=1724555893~hmac=55a1de87be1b7e1f429411f972bbfc03fc1a3536fa36fa0c2b6ed43b923bd41c",
    "duration": "11:10",
    "views": "10,000,000",
    "author": "YouTube Auto",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    "description": "Your last watched content overview.",
    "subscriber": "N/A",
    "isLive": false,
    "channelId": "chWatch",
    "uploader": "UserWT1",
    "likes": 110,
    "dislikes": 3,
    "uploadDate": "2024-02-22",
    "comments": [],
    "category": "Watched"
  },

  {
    "id": "20",
    "videoId": "tech01",
    "title": "AI Technology Changing the World",
    "thumbnailUrl": "https://img.freepik.com/free-psd/metaverse-poses-backgrounds_23-2150145319.jpg",
    "photo": "https://img.freepik.com/free-psd/metaverse-poses-backgrounds_23-2150145319.jpg",
    "duration": "12:18",
    "views": "24,969,123",
    "author": "TechVision",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "description": "How AI is transforming industries.",
    "subscriber": "1,240,000 Subscribers",
    "isLive": false,
    "channelId": "chTech",
    "uploader": "UserTech1",
    "likes": 640,
    "dislikes": 18,
    "uploadDate": "2024-02-28",
    "comments": [],
    "category": "Technology"
  },

  {
    "id": "21",
    "videoId": "sci01",
    "title": "The Secrets of Quantum Physics",
    "thumbnailUrl": "https://static.vecteezy.com/system/resources/previews/022/006/638/non_2x/science-background-illustration-scientific-design-flasks-glass-and-chemistry-physics-elements-generative-ai-photo.jpeg",
    "photo": "https://static.vecteezy.com/system/resources/previews/022/006/638/non_2x/science-background-illustration-scientific-design-flasks-glass-and-chemistry-physics-elements-generative-ai-photo.jpeg",
    "duration": "18:40",
    "views": "3,421,221",
    "author": "Science Lab",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "description": "Exploring the mysteries of quantum mechanics.",
    "subscriber": "820,000 Subscribers",
    "isLive": false,
    "channelId": "chSci",
    "uploader": "UserSci1",
    "likes": 510,
    "dislikes": 9,
    "uploadDate": "2024-02-20",
    "comments": [],
    "category": "Science"
  },

  {
    "id": "22",
    "videoId": "edu01",
    "title": "The Complete History of Human Civilization",
    "thumbnailUrl": "https://i.ytimg.com/vi_webp/dQw4w9WgXcQ/maxresdefault.webp",
    "photo": "https://i.ytimg.com/vi_webp/dQw4w9WgXcQ/maxresdefault.webp",
    "duration": "25:00",
    "views": "12,453,980",
    "author": "EduWorld",
    "videoUrl": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    "description": "An educational journey through human civilization.",
    "subscriber": "560,000 Subscribers",
    "isLive": false,
    "channelId": "chEdu",
    "uploader": "UserEdu1",
    "likes": 820,
    "dislikes": 22,
    "uploadDate": "2024-02-18",
    "comments": [],
    "category": "Education"
  }  
]